---
- name: set /opt/monit/monitrc template
  when: aspects_monit_enabled
  template:
    src: "opt-monit-monitrc.j2"
    dest: "/opt/monit/monitrc"
    owner: "root"
    group: "root"
    mode: "600"
  notify: restart manual_monit
  tags:
  - aspects_monit
  - aspects_monit_config
  - aspects_monit_configure

- name: set /etc/pam.d/monit template
  when: aspects_monit_enabled
  template:
    src: "etc-pam.d-monit.j2"
    dest: "/etc/pam.d/monit"
    owner: "root"
    group: "root"
    mode: "644"
  notify: restart manual_monit
  tags:
  - aspects_monit
  - aspects_monit_config
  - aspects_monit_configure