---
- name: Include manual install tasks
  when:
    - aspects_monit_run_manual_install
    - aspects_monit_use_manual_tasks
    - aspects_monit_run_update
  include_tasks: installManual.yml
  tags:
    - aspects_monit
    - aspects_monit_install

- name: Make sure /etc/monit exists
  file:
    state: directory
    path: /etc/monit
    owner: root
    group: root
    mode: "0750"
  tags:
    - aspects_monit
    - aspects_monit_config

- name: Include Debian Configuration tasks
  when:
    - ansible_os_family == "Debian"
    - aspects_monit_use_manual_tasks == False
  include_tasks: configureDebian.yml
  tags:
    - aspects_monit
    - aspects_monit_config

- name: Include RedHat Configuration tasks
  when:
    - ansible_os_family == "RedHat"
    - aspects_monit_use_manual_tasks == False
  include_tasks: configureRedHat.yml
  tags:
    - aspects_monit
    - aspects_monit_config

- name: Include manual Configuration tasks
  when: aspects_monit_use_manual_tasks == True
  include_tasks: configureManual.yml
  tags:
    - aspects_monit
    - aspects_monit_config

- name: Include update tasks
  when:
    - aspects_monit_run_update
    - (ansible_os_family == "Debian" or ansible_os_family == "RedHat")
    - aspects_monit_use_manual_tasks == False
  include_tasks: update.yml
  tags:
    - aspects_monit
    - aspects_monit_update

- name: CentOS 7 - Add /etc/pam.d/monit file
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
  template:
    src: etc-pam.d-monit.j2
    dest: /etc/pam.d/monit
    owner: root
    group: root
  tags:
    - aspects_monit

- name: OracleLinux 7 - Add /etc/pam.d/monit file
  when:
  - ansible_distribution == "OracleLinux"
  - ansible_distribution_major_version == "7"
  template:
    src: etc-pam.d-monit.j2
    dest: /etc/pam.d/monit
    owner: root
    group: root
  tags:
  - aspects_monit

- include: installLdapTest.yml
  when: aspects_monit_use_ldap_test == true
  tags:
    - aspects_monit

- name: create htpasswd users
#  no_log: True
  htpasswd:
    state: "{{ item.1.state }}"
    create: "yes"
    path: "{{ aspects_monit_htpasswd_path }}"
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    crypt_scheme: "{{ item.1.crypt_scheme }}"
  loop: "{{ aspects_monit_htpasswd_users | default({}) | dictsort }}"
  tags:
    - aspects_monit
    - aspects_monit_htpasswd