---
- name: Debian - Install python-apt for use with ansible apt modules.
  apt:
    pkg: python-apt
    state: present
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: Debian - Install monit
  apt:
    pkg: "monit"
    state: "present"
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: Debian - Install python-passlib
  when: aspects_monit_htpasswd_users is defined
  apt:
    pkg: "python-passlib"
    state: "present"
  tags:
  - aspects_monit
  - aspects_monit_run_install