---
- name: setup monit directories.
  when: aspects_monit_enabled
  file:
    state: directory
    path: "{{ item }}"
    owner: root
    group: root
    mode: 750
  loop:
  - /opt/monit
  - /opt/monit/bin
  - /opt/monit/id
  - /opt/monit/state
  - /opt/monit/events
  - /opt/monit/conf.d
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: copy monit excutable
  when: aspects_monit_enabled
  copy:
    src: "{{ aspects_monit_update_excutable_relative_path }}"
    dest: /opt/monit/bin/monit
    mode: 700
    owner: root
    group: root
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: copy monit restart script
  when: aspects_monit_enabled
  copy:
    src: "restartmonit.sh"
    dest: /opt/monit/bin/restartmonit.sh
    mode: 700
    owner: root
    group: root
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: Set cron job so monit starts on boot
  when: aspects_monit_enabled
  cron:
    name: "aspects_monit - start monit at boot"
    state: "present"
    cron_file: monit
    user: root
    special_time: "reboot"
    job: "/opt/monit/bin/monit -c /opt/monit/monitrc"
  tags:
  - aspects_monit
  - aspects_monit_run_install