---
- name: Debian - Install python-apt for use with ansible apt modules.
  when: ansible_os_family == "Debian"
  apt: pkg=python-apt state=latest update_cache="yes" cache_valid_time="86400"
  tags:
    - aspects_monit_packages

- name: Debian - Set monit packages state with apt
  when: ansible_os_family == "Debian" and item.value.state != 'default' and item.value.state != 'purged' and item.value.Debian is defined
  apt: pkg={{ item.value.Debian }} state={{ item.value.state }} update_cache="yes" cache_valid_time="86400"
  with_dict: aspects_monit_packages
  tags:
    - aspects_monit_packages
