---
- name: RedHat - Install epel-release
  yum:
    name: "epel-release"
    state: "present"
    update_cache: "yes"
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: RedHat - Create /var/lib/monit/ directory
  file:
    state: directory
    path: /var/lib/monit/
    owner: root
    group: root
    mode: 750
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: RedHat - Install monit
  yum:
    name: "monit"
    state: "present"
    update_cache: "yes"
  tags:
  - aspects_monit
  - aspects_monit_run_install

- name: RedHat - Install python-passlib
  when: aspects_monit_htpasswd_users is defined
  yum:
    name: "python-passlib"
    state: "present"
    update_cache: "yes"
  tags:
  - aspects_monit
  - aspects_monit_run_install