---
# only runs when aspects_monit_use_ldap_test = yes
- name: Set ldap server authentication test script templates.
  template:
    src: "ldaptest.sh.j2"
    dest: "/root/scripts/{{ item.value.name }}.ldaptest.sh"
    mode: 700
    owner: root
    group: root
  loop: "{{ aspects_monit_ldap_test_config|dict2items }}"
  tags:
    - aspects_monit
