---
# handlers file for aspects_monit
#- name: restart monit
#  service: name=monit state=restarted enabled=yes

- name: reload monit
  shell: /opt/monit/bin/monit -c /opt/monit/monitrc reload
#  service: name=monit state=reloaded enabled=yes

- name: start monit
  shell: /opt/monit/bin/monit -c /opt/monit/monitrc
#  service: name=monit state=started enabled=yes

- name: stop monit
  shell: /opt/monit/bin/monit -c /opt/monit/monitrc quit
#  service: name=monit state=stopped

- name: restart monit
  shell: chdir="/opt/monit/bin/" /bin/bash restartmonit.sh