---
# Handlers for running repo install monit.
- name: restart monit
  service:
    name: monit
    state: restarted
    enabled: yes
  tags:
  - aspects_monit
  - aspects_monit_handlers

- name: start monit
  service:
    name: monit
    state: started
    enabled: yes
  tags:
  - aspects_monit
  - aspects_monit_handlers

- name: stop monit
  service:
    name: monit
    state: stopped
    enabled: yes
  tags:
  - aspects_monit
  - aspects_monit_handlers

# Handlers for running manually installed monit.
- name: reload manual_monit
  shell: /opt/monit/bin/monit -c /opt/monit/monitrc reload
  tags:
  - aspects_monit
  - aspects_monit_handlers

- name: start manual_monit
  shell: /opt/monit/bin/monit -c /opt/monit/monitrc
  tags:
  - aspects_monit
  - aspects_monit_handlers

- name: stop manual_monit
  shell: /opt/monit/bin/monit -c /opt/monit/monitrc quit
  tags:
  - aspects_monit
  - aspects_monit_handlers

- name: restart manual_monit
  shell: /bin/bash restartmonit.sh
  args:
    chdir: "/opt/monit/bin/"
  tags:
  - aspects_monit
  - aspects_monit_handlers
